/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "dmtuhobmqzdlwcpnjuli"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtdHVob2JtcXpkbHdjcG5qdWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDkzODksImV4cCI6MjA3MzMyNTM4OX0.2dz9UPomAN3P5NGgU93hT8OFbqvA-D6PYpMvB1WLNuY"
export const edgeFunctionName = import.meta.env.VITE_EDGE_FUNCTION_NAME || "make-server-72dfd380"